-- Intervals
INSERT INTO Tag (category, label) VALUES
('Interval', 'Minor Second'),
('Interval', 'Major Second'),
('Interval', 'Minor Third'),
('Interval', 'Major Third'),
('Interval', 'Perfect Fourth'),
('Interval', 'Tritone / Augmented Fourth / Diminished Fifth'),
('Interval', 'Perfect Fifth'),
('Interval', 'Minor Sixth'),
('Interval', 'Major Sixth'),
('Interval', 'Minor Seventh'),
('Interval', 'Major Seventh'),
('Interval', 'Octave'),
('Interval', 'Minor Ninth'),
('Interval', 'Major Ninth'),
('Interval', 'Augmented Ninth'),
('Interval', 'Minor Tenth'),
('Interval', 'Major Tenth'),
('Interval', 'Perfect Eleventh'),
('Interval', 'Augmented Eleventh'),
('Interval', 'Perfect Twelfth'),
('Interval', 'Minor Thirteenth'),
('Interval', 'Major Thirteenth'),
('Interval', 'Augmented Thirteenth'),
('Interval', 'Double Octave');

-- Protocol
INSERT INTO Tag (category, label) VALUES
('Protocol', 'Brr'),
('Protocol', 'Ng'),
('Protocol', 'Cry'),
('Protocol', 'Connection'),
('Protocol', 'Space (K)'),
('Protocol', 'Space (H)'),
('Protocol', 'Classic Twang'),
('Protocol', 'Modern Twang'),
('Protocol', 'Mix'),
('Protocol', 'Mix 1'),
('Protocol', 'Mix 2'),
('Protocol', 'Belt'),
('Protocol', 'Falsetto'),
('Protocol', 'Whistle'),
('Protocol', 'Vocal Fry'),
('Protocol', 'Humming'),
('Protocol', 'Rolled R'),
('Protocol', 'Singing Speech'),
('Protocol', 'Sob');

-- Objective
INSERT INTO Tag (category, label) VALUES
('Objective', 'Resonance'),
('Objective', 'Stability'),
('Objective', 'Vibrato'),
('Objective', 'Tremolo'),
('Objective', 'Glissando'),
('Objective', 'Forte'),
('Objective', 'Piano'),
('Objective', 'Crescendo'),
('Objective', 'Decrescendo'),
('Objective', 'Articulation'),
('Objective', 'Yodel'),
('Objective', 'High Notes'),
('Objective', 'Low Notes'),
('Objective', 'Breath Support'),
('Objective', 'Breath Sustain'),
('Objective', 'Agility'),
('Objective', 'Legato'),
('Objective', 'Staccato'),
('Objective', 'Ear Training'),
('Objective', 'Melisma'),
('Objective', 'Riffs and Runs');

-- Scale
INSERT INTO Tag (category, label) VALUES
('Scale', 'Major'),
('Scale', 'Natural Minor'),
('Scale', 'Harmonic Minor'),
('Scale', 'Melodic Minor'),
('Scale', 'Major Pentatonic'),
('Scale', 'Minor Pentatonic'),
('Scale', 'Major Blues'),
('Scale', 'Minor Blues'),
('Scale', 'Ionian'),
('Scale', 'Dorian'),
('Scale', 'Phrygian'),
('Scale', 'Lydian'),
('Scale', 'Mixolydian'),
('Scale', 'Aeolian'),
('Scale', 'Locrian'),
('Scale', 'Chromatic'),
('Scale', 'Diminished Octatonic'),
('Scale', 'Whole Tone Augmented'),
('Scale', 'Phrygian Dominant'),
('Scale', 'Tritone Hexatonic'),
('Scale', 'Super Locrian');